services:
  pgsql:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hermes
    ports:
      - '5432:5432'
  redis:
    image: redis
    ports:
      - '6379:6379'
  pubsub:
    image: redis
    ports:
      - '7963:7963'
