services:
  pgsql:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hermes
    ports:
      - '5432:5432'
  redis:
    image: redis
    command: redis-server --requirepass password
    ports:
      - '6379:6379'
  pubsub:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - '5672:5672'
      - '15672:15672'
